repositories:
  custom-repo:
    url: https://github.com/hmthanh/OHGesture

global:
  install_dir: ~/deepgesture

dependencies:
  - absl-py
  - accelerate
  - annotated-types
  - antlr4-python3-runtime
  - anyascii
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - attrs
  - audioread
  - Babel
  - bleach
  - blis
  - blobfile
  - Brotli
  - cached-property
  - catalogue
  - certifi
  - cffi
  - charset-normalizer
  - click
  - cloudpathlib
  - cloup
  - colorlog
  - colour
  - comm
  - confection
  - ConfigArgParse
  - contourpy
  - contractions
  - cycler
  - cymem
  - Cython
  - debugpy
  - decorator
  - defusedxml
  - easydict
  - einops
  - ema-pytorch
  - entrypoints
  - exceptiongroup
  - executing
  - fastjsonschema
  - fasttext
  - ffmpeg-normalize
  - ffmpeg-progress-yield
  - filelock
  - fqdn
  - fsspec
  - gensim
  - glcontext
  - gmpy2
  - grpcio
  - h11
  - h2
  - h5py
  - hpack
  - httpcore
  - httpx
  - huggingface-hub
  - hyperframe
  - HyperPyYAML
  - idna
  - ipykernel
  - ipython
  - ipywidgets
  - isoduration
  - isosurfaces
  - jedi
  - Jinja2
  - joblib
  - json5
  - jsonpointer
  - jsonschema
  - kiwisolver
  - langcodes
  - language_data
  - lazy_loader
  - librosa
  - lmdb
  - lxml
  - marisa-trie
  - Markdown
  - markdown-it-py
  - MarkupSafe
  - matplotlib
  - matplotlib-inline
  - mdurl
  - mido
  - mistune
  - moderngl
  - moderngl-window
  - mpld3
  - mpmath
  - msgpack
  - multipledispatch
  - munkres
  - murmurhash
  - nbclient
  - nbconvert
  - nbformat
  - nest_asyncio
  - networkx
  - nltk
  - notebook
  - notebook_shim
  - numba
  - numpy
  - omegaconf
  - onnx
  - opencv-python
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pkgutil_resolve_name
  - platformdirs
  - plotly
  - pooch
  - praatio
  - preshed
  - progressbar
  - prometheus_client
  - prompt_toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pure_eval
  - pyahocorasick
  - pyarrow
  - pybind11
  - pycairo
  - pycparser
  - pycryptodomex
  - pydantic
  - pydub
  - pyglet
  - Pygments
  - pymongo
  - pyobjc-core
  - pyobjc-framework-Cocoa
  - PyOpenGL
  - pyparsing
  - pyrr
  - PySnooper
  - PySocks
  - python-dateutil
  - python-json-logger
  - pytz
  - PyYAML
  - pyzmq
  - referencing
  - regex
  - requests
  - rich
  - safetensors
  - scikit-learn
  - scipy
  - screeninfo
  - seaborn
  - Send2Trash
  - sentencepiece
  - six
  - sniffio
  - soundfile
  - sox
  - soxr
  - spacy
  - spacy-legacy
  - spacy-loggers
  - srsly
  - srt
  - stack-data
  - svgelements
  - sympy
  - tenacity
  - tensorboard
  - tensorflow-estimator
  - termcolor
  - terminado
  - textgrid
  - thinc
  - threadpoolctl
  - tinycss2
  - toml
  - tomli
  - toolz
  - torch
  - torchaudio
  - torchmetrics
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - transformers
  - typing-extensions
  - tzlocal
  - urllib3
  - virtualenv
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - widgetsnbextension
  - wrapt
  - wurlitzer
  - xgboost
  - xyzservices
  - y-py
  - yapf
  - yarl
  - zipp
  - zstandard
