# ZEGGS
processing_train_data_path: "../ZeroEGGSProcessing/processed/train/"     # speaker_1_state_0
processing_val_data_path: "../ZeroEGGSProcessing/processed/valid/"

train_dataset_path: "../ZeroEGGSProcessing/h5dataset/train/"     # speaker_1_state_0
valid_dataset_path: "../ZeroEGGSProcessing/h5dataset/valid/"

train_h5: "../ZeroEGGSProcessing/h5dataset/datasets_train.h5"
valid_h5: "../ZeroEGGSProcessing/h5dataset/datasets_valid.h5"

# 60 fps + normalized
gesture_mean: "../ZeroEGGSProcessing/processed/mean.npz"
gesture_std: "../ZeroEGGSProcessing/processed/std.npz"

# wavlm_model_path: './WavLM/WavLM-Large.pt'
wavlm_model_path: './wavlm/WavLM-Large.pt'

# --------- FEATURE ---------
# feature
n_poses: 88     # 88 -> 20*60
n_codes: 30
motion_resampling_framerate: 20     # 20 -> 60
subdivision_stride: 10      # 10 -> 200
batch_size: 1152       # 384 -> 32

# --------- FEATURE ---------
loader_workers: 2
epochs: 1 # 500     # 500 -> 10
save_per_epochs: 25     # 20 -> 1


model_save_path: "./output/train_OHGesture"
name: "OHGesture"
log_interval: 50
weight_decay: 0.0
lr_anneal_steps: 0
save_dir: "./save_dir/ohgesture"
audio_feat: "wavlm"     # wav encoder; mfcc; wavlm

lr: 0.00003     # 0.00003 ->
betas: [0.5, 0.999]
milestones: [100, 200]

# --------- Hyperparameters ---------
gamma: 0.1

