import contractions


if __name__ == '__main__':
    # Example contractions
    # text = "I think the worst food that would be liquefied and drank through a straw would be something meaty , because I do not think that would liquefy well . Like , I ca not imagine eating drinking a steak , but maybe I  will feel about it differently when I 'm old . I think that I can do almost anything better than 90 percent of the people , because as I look around me and I see the people and humanity and the actions of others , I feel that I 'm just better than everyone else . The most amazing nature place that I 've been to definitely has to be in Canada , maybe probably even Quebec have been going in the eastern townships and walking through the forest and seeing the different animals running around . There was really a great experience and I was really happy to be there when I was there . The next thing to be obsolete . Oh , it 's hard to imagine . I try to see what 's around me . Maybe motion capture , maybe data sets something to think about while we  are doing this exercise . Hopefully not the technology we  are developing right now . The most annoying animal in the animal kingdom , without a doubt , is the beaver , because it just chews on things and it creates dams and it stops water . It 's just making a mess ."
    text = "I think the worst food that would be liquefied and drank through a straw would be something meaty, because I don't think that would liquefy well. Like, I can't imagine eating drinking a steak, but maybe I'll feel about it differently when I'm old. I think that I can do almost anything better than 90 percent of the people, because as I look around me and I see the people and humanity and the actions of others, I feel that I'm just better than everyone else. The most amazing nature place that I've been to definitely has to be in Canada, maybe probably even Quebec have been going in the eastern townships and walking through the forest and seeing the different animals running around. There was really a great experience and I was really happy to be there when I was there. The next thing to be obsolete. Oh, it's hard to imagine. I try to see what's around me. Maybe motion capture, maybe data sets something to think about while we're doing this exercise. Hopefully not the technology we're developing right now. The most annoying animal in the animal kingdom, without a doubt, is the beaver, because it just chews on things and it creates dams and it stops water. It's just making a mess."
    # Expanding contractions
    expanded_text = contractions.fix(text)

    print(expanded_text)
